server:
  port: 8080
spring:
  application:
    name: Athena
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/athena?serverTimezone=Asia/Shanghai
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: Share@2498
  redis:
    host: localhost
    port: 6379
    database: 10
    password: Share@2498
jwt:
  secret: TGF1SG9uYmFu
  expiration: 3600
  header: Bearer