server:
  port: 8080
spring:
  application:
    name: Athena
  data:
    mongodb:
      authentication-database: admin
      database: Athena
      host: 127.0.0.1
      port: 27017
      username: root
      password: Share@2498
  redis:
    host: 127.0.0.1
    port: 6379
    password: Share@2498
    database: 0
logging:
  level:
    org.springframework.data.mongodb.core: debug
    org.springframework.data.mongodb.repository: debug
jwt:
  secret: TGF1SG9uYmFu
  expiration: 3600
  header: Bearer
